title: Frontier Primary School
url: https://frontierpri.moe.edu.sg
favicon: /images/logo2.png
colors:
  primary-color: "#f28500"
  secondary-color: "#464646"
  media-colors:
    - title: media-color-one
      color: "#000000"
    - title: media-color-two
      color: "#f28500"
    - title: media-color-three
      color: "#028a0f"
    - title: media-color-four
      color: "#028a0f"
    - title: media-color-five
      color: "#028a0f"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d331543a351h7b.amplifyapp.com
prod: https://master.d331543a351h7b.amplifyapp.com
shareicon: /images/logo2.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: frontier-primary
